<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Applications.aspx.cs" Inherits="Applications" %>

<!DOCTYPE html>

<style>

body, html{
    font-family: Helvetica,sans-serif;
    font-size: 14px;
    line-height: 1.45em;
    color: #3A3A3A;
    background-color: #EFEFEF;
}
.data_block{
    display:inline;
    margin-left: 20px; 
    padding-left: 20px;
    width:220px;
    list-style-type: none;
    border:1px solid #000;
    }
.textbox_data ul
{
    padding: 0;
    list-style-type: none;
    border:1px solid #000;
    float:left;
    margin-left:5px;
    margin-top:10px;
    width:515px;
    height:670px;
    overflow-y:scroll;
    overflow-x:hidden;
}
.textbox_data ul li {
    margin-left:5px;
    width:495px;
    display:inline-block;
}
.textbox_data ul li label{
    width:150px;
}
.liHeaderBold {

}
.dTxBx {
    margin-left:10px;
    width:350px;
    float:right;
    margin-right:5px;
}

.menu_simple ul {
    margin: 0; 
    padding: 0;
    width:220px;
    list-style-type: none;
    border:1px solid #000;
    float:left;
    background-color:#fff;
}
.menu_simple ul li a {
    text-decoration: none;
    color: black; 
    padding: 5.5px 11px;
    display:block;
    width: 198px;
    cursor:default;
}
.menu_simple ul li a:visited {
    color: black;
} 
.menu_simple ul li a:hover, .menu_simple ul li .current {
    color: black;
    background-color: #caf1fa;
}
.sysinfotxt
{
    margin-left:10px;
    width:350px;
    float:right;
    margin-right:5px
}
.sysinfolabel
{

}
.sysinfoheader
{

}
    body, html{
    font-family: Helvetica,sans-serif;
    font-size: 14px;
    line-height: 1.45em;
    color: #3A3A3A;

}
.myGrid {
    background-color: #fff;
    border: solid 1px #525252;
    border-collapse:collapse;
}
.myGrid td{
    padding: 2px;
    border:solid 1px #c1c1c1;
    white-space: nowrap;
}
.myGrid th {
    padding: 4px 2px;
    color: #fff;
    background-color: #8F9393;
    border-left: solid 1px #525252;
    font-size: 0.9em;
}
.imtip
{
position:absolute;
bottom:0;
right:0;
}
a:link {
    color: #000;
}

/* visited link */
a:visited {
    color: #ff6a00;
}

/* mouse over link */
a:hover {
    color: #000;
}

/* selected link */
a:active {
    color: #0000FF;
}
th {
        padding: 4px 2px;
        border: solid 1px #c1c1c1;   
        font-size: 0.9em;
        cursor: pointer;
    }
    th:hover
    {
        background-color: #717171;
    }
    tr:nth-child(even)
    {
        background-color:#EFEFEF;
    }

   
    /* Prevents the damn auto clear generated by asp:menu */

#FCol
{
    width:auto;
    overflow-y:hidden;
    overflow-x:scroll;
}
</style>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
        <script src="/scripts/jquery-1.11.3.js"></script>
    <script>
        
        function hvrstart(sender)
        {
            $('.' + sender).css("background-color", "#8F9393");
            
        }
        function hvrleave(sender) {
            $('.' + sender).css("background-color", "");
        }
    $(document).ready(function () {
        // here clone our gridview first
       
                    var tab = $("#<%=GridView1.ClientID%>").clone(true);
                    // clone again for freeze
                    var tabFreeze = $("#<%=GridView1.ClientID%>").clone(true);
 
                    // set width (for scroll)
                    var totalWidth = $("#<%=GridView1.ClientID%>").outerWidth();
                    var firstColWidth = $("#<%=GridView1.ClientID%> th:first-child").outerWidth();
                    tabFreeze.width(firstColWidth);
                    tab.width(totalWidth - firstColWidth);
 
                    // here make 2 table 1 for freeze column 2 for all remain column
 
                    tabFreeze.find("th:gt(0)").remove();
                    tabFreeze.find("td:not(:first-child)").remove();
 
                    tab.find("th:first-child").remove();
                    tab.find("td:first-child").remove();
 
                    // create a container for these 2 table and make 2nd table scrollable
            
                    var container = $('<table border="0" cellpadding="0" cellspacing="0"><tr><td valign="top"><div id="FCol" style="margin-left:5px;border:solid 1px #525252;border-right:none;"></div></td><td valign="top"><div id="Col" style="border:solid 1px #525252;overflow:auto"></div></td></tr></table)');
                       $("#FCol", container).html($(tabFreeze));
                    $("#Col", container).html($(tab));
 
                    // clear all html
                    $("#gridContainer").html('');
                    $("#gridContainer").append(container);

                    $('#Col').on('scroll', function () {
                        $('#FCol').scrollTop($(this).scrollTop());
                        $("#h01").html($(this).scrollTop());
                    });
                    $('#Col').height($(window).height() - 100);

                    $('#FCol').height($(window).height() - 100);
                    $('#Col').width($(window).width() - 1000);
    });
    
</script>
</head>
<body>
    <form id="form1" runat="server">
                
    <div>
                    <div class="menu_simple" ">
                        <ul>
                            <li><a runat="server" id="computer" href="/Computer.aspx?computer="><asp:image runat="server" id="computer_img" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Computer</a></li>
                             <li><a runat="server" id="ad_groups" href="/ad_groups.aspx?computer="><img src="img/icon-adgroups.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Active Directory Groups</a></li>
                             <li><a runat="server" id="applications" href="/Applications.aspx?computer="><img src="img/applications.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Applications</a></li>
                             <li><a runat="server" id="custom_items" href="/custom_items.aspx?computer="><img src="img/custom_items.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Custom Items</a></li>
                             <li><a runat="server" id="disk_drives" href="/disk_drives.aspx?computer="><img src="img/disk_drives.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Disk Drives</a></li>
                             <li><a runat="server" id="displays" href="/Applications.aspx?computer="><img src="img/displays.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Displays</a></li>
                             <li><a runat="server" id="environment" href="/environment.aspx?computer="><img src="img/environment.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Environment</a></li>
                             <li><a runat="server" id="files" href="/files.aspx?computer="><img src="img/62.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Files</a></li>
                             <li><a runat="server" id="hardware" href="/hardware.aspx?computer="><img src="img/hardware.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/> Hardware</a></li>
                             <li><a runat="server" id="hot_fixes" href="/hot_fixes.aspx?computer="><img src="img/hot_fixes.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Hot Fixes</a></li>
                             <li><a runat="server" id="local_groups" href="/local_groups.aspx?computer="><img src="img/local_groups.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Local Groups</a></li>
                             <li><a runat="server" id="local_users" href="/local_users.aspx?computer="><img src="img/local_users.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Local Users</a></li>
                             <li><a runat="server" id="memory" href="/memory.aspx?computer="><img src="img/memory.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Memory Modules</a></li>
                             <li><a runat="server" id="nics" href="/nics.aspx?computer="><img src="img/nics.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  NICs</a></li>
                             <li><a runat="server" id="printers" href="/printers.aspx?computer="><img src="img/unknown.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Printers</a></li>
                             <li><a runat="server" id="processes" href="/processes.aspx?computer="><img src="img/processes.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Processes</a></li>
                             <li><a runat="server" id="product_keys" href="/product_keys.aspx?computer="><img src="img/product_keys.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Product Keys</a></li>
                             <li><a runat="server" id="registry" href="/registry.aspx?computer="><img src="img/registry.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Registry</a></li>
                             <li><a runat="server" id="scans" href="/scans.aspx?computer="><img src="img/scans.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Scans</a></li>
                             <li><a runat="server" id="services" href="/services.aspx?computer="><img src="img/services.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/> Services</a></li>
                             <li><a runat="server" id="shares" href="/shares.aspx?computer="><img src="img/shares.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Shares</a></li>
                             <li><a runat="server" id="windows_features" href="/windows_features.aspx?computer="><img src="img/windows_features.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Windows Features</a></li>
                             <li><a runat="server" id="windows_task_schedules" href="/windows_task_schedules.aspx?computer="><img src="img/windows_task_schedules.png" style='vertical-align:middle;margin-bottom:3px;' height='15' width='15'/>  Windows Task Schedules</a></li>
</ul>
                       <asp:Label ID="Label1" runat="server" style="margin-left:20px;font-size:18px;" Text="Label"></asp:Label>

                            
                    </div>
                    <div id="gridContainer" style="height: 500px;margin-left:5px;margin-top:10px">

                <asp:GridView CssClass="myGrid"  ID="GridView1" runat="server" OnRowDataBound="GridView1_RowDataBound" AllowSorting="True" OnSorting="GridView1_Sorting" OnSelectedIndexChanged="GridView1_SelectedIndexChanged"/>
                <asp:Literal runat="server" id="txtValueA" EnableViewState="false" />
            </div>
       
    </div>
    </form>
</body>
</html>
