<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html>

<style>
    #document {display: none;}
    body, html{
    font-family: Helvetica,sans-serif;
    font-size: 14px;
    line-height: 1.45em;
    color: #3A3A3A;
    background-color: #EFEFEF;
}

.myGrid {
    background-color: #fff;
    border: solid 1px #525252;
    border-collapse:collapse;
}
.myGrid td{
    padding: 2px;
    border:solid 1px #c1c1c1;
    white-space: nowrap;
}
.myGrid th {
    padding: 4px 2px;
    color: #fff;
    background-color: #8F9393;
    border-left: solid 1px #525252;
    font-size: 0.9em;
}

.imtip
{
position:absolute;
bottom:0;
right:0;
}
a:link {
    color: #000;
}

/* visited link */
a:visited {
    color: #ff6a00;
}

/* mouse over link */
a:hover {
    color: #000;
}

/* selected link */
a:active {
    color: #0000FF;
}
th {
        padding: 4px 2px;
        border: solid 1px #c1c1c1;   
        font-size: 0.9em;
        cursor: pointer;
    }
    th:hover
    {
        background-color: #717171;
    }
    tr:nth-child(even)
    {
        background-color:#EFEFEF;
    }

   
    /* Prevents the damn auto clear generated by asp:menu */

#FCol
{
    width:auto;
    overflow-y:hidden;
    overflow-x:scroll;
}
.tree td img
{
    vertical-align: bottom;
}
</style>




<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <script src="/scripts/jquery-1.11.3.js"></script>
    <script>
        
        function hvrstart(sender)
        {
            $('.' + sender).css("background-color", "#8F9393");
            
        }
        function hvrleave(sender) {
            $('.' + sender).css("background-color", "");
        }
    $(document).ready(function () {
        // here clone our gridview first
                    
                    var tab = $("#<%=GridView1.ClientID%>").clone(true);
                    // clone again for freeze
                    var tabFreeze = $("#<%=GridView1.ClientID%>").clone(true);
 
                    // set width (for scroll)
                    var totalWidth = $("#<%=GridView1.ClientID%>").outerWidth();
                    var firstColWidth = $("#<%=GridView1.ClientID%> th:first-child").outerWidth();
                    tabFreeze.width(firstColWidth);
                    tab.width(totalWidth - firstColWidth);
 
                    // here make 2 table 1 for freeze column 2 for all remain column
 
                    tabFreeze.find("th:gt(0)").remove();
                    tabFreeze.find("td:not(:first-child)").remove();
 
                    tab.find("th:first-child").remove();
                    tab.find("td:first-child").remove();
 
                    // create a container for these 2 table and make 2nd table scrollable
            
                    var container = $('<table border="0" cellpadding="0" cellspacing="0"><tr><td valign="top"><div id="FCol" style="border:solid 1px #525252;border-right:none;"></div></td><td valign="top"><div id="Col" style="border:solid 1px #525252;overflow:auto"></div></td></tr></table)');
                       $("#FCol", container).html($(tabFreeze));
                    $("#Col", container).html($(tab));
 
                    // clear all html
                    $("#gridContainer").html('');
                    $("#gridContainer").append(container);

                    $('#Col').on('scroll', function () {
                        $('#FCol').scrollTop($(this).scrollTop());
                        $("#h01").html($(this).scrollTop());
                    });
                    $('#Col').height($(window).height() - 150);
                    $('#FCol').height($(window).height() - 150);
                    $('#Col').width($(window).width() - 600);

                    $('#TreeView1').height($(window).height() - 100);
                    $("#document").show();
    });
    
</script>
</head>
    <body>
        <div id="document">
            <h1 runat="server" id="h01">Test</h1>
            <asp:Literal runat="server" id="txtValueA" EnableViewState="false" >txtTest</asp:Literal>
            <form id="form1" runat="server">
                <div style ="border:1px solid #000;display:inline-block">
                  <asp:TreeView ID="TreeView1" style="display:inline-block;overflow-y:scroll" ImageSet="Arrows" runat="server">
                      <HoverNodeStyle Font-Underline="True" ForeColor="#5555DD" />
                    <Nodes>
                    </Nodes>
                      <NodeStyle Font-Names="Tahoma" Font-Size="10pt" ForeColor="Black" HorizontalPadding="5px" NodeSpacing="0px" VerticalPadding="0px" />
                      <ParentNodeStyle Font-Bold="False" />
                      <SelectedNodeStyle Font-Underline="True" ForeColor="#5555DD" HorizontalPadding="0px" VerticalPadding="0px" />
                  </asp:TreeView>
                </div>
                <div id="gridContainer" style="
        display:inline-block;  
        position: fixed;
        margin-top: 50px;
        margin-left: 10px;">
                    <asp:GridView CssClass="myGrid"  ID="GridView1" runat="server" OnRowDataBound="GridView1_RowDataBound" AllowSorting="True" OnSorting="GridView1_Sorting" OnSelectedIndexChanged="GridView1_SelectedIndexChanged"/>
                    
                </div>                 
            </form>
        </div>
    </body>
</html>


